### ISSUE TITLE
Don't remove line numbers with `sed` in cleanup.win

### ISSUE THREAD

**Issue by jgabry** [stan-dev/rstantools#1]
Reported by Slawek Smyl on [Stan-users](https://groups.google.com/forum/#!category-topic/stan-users/XD20kvilP_c):

> **rstantools** creates a skeleton with `cleanup.win` file that contains call to `sed`
> 
>   `sed -i.bak '/current_statement_begin__ = [0-9]/d' src/include/models.hpp`
> 
> The problem is that on Windows, GNU `sed` will change permissions (drastically reduce them)  of the edited file, making  `models.hpp` unreachable
> 
> `Modules.cpp:3:30: fatal error: include/models.hpp: Permission denied`
> 
> It is apparently a well known bug of sed, e.g. https://cygwin.com/ml/cygwin/2012-02/msg00616.html
>

**Comment by bgoodri** [comment]
This was fixed in rstanarm
