### ISSUE TITLE
rstantools::loo_pit sometimes returns values larger than 1

### ISSUE THREAD

**Issue by avehtari** [stan-dev/rstantools#11]
@jgabry has access to the data and then should be able to reproduce

mod3 = stan_glmer(log_pm25 ~ log_sat_2014 + (log_sat_2014 | cluster_region), 
                  data=GMs@data)
psis3 <- psislw(-log_lik(mod3))
pit3 <- rstantools::loo_pit(object = posterior_predict(mod3), y = log(GMs@data$pm25), lw = psis3$lw_smooth)
> max(pit3)-1
[1] 8.881784e-16

pit values should be between 0 and 1

**Comment by jgabry** [comment]
I'll look into this. Thanks for letting me know.

**Comment by andrjohns** [comment]
Is this safe to close, or is the bug still present? @jgabry @avehtari

**Comment by avehtari** [comment]
Closed by #121
