### ISSUE TITLE
Licence question

### ISSUE THREAD

**Issue by jan-glx** [stan-dev/rstantools#17]
Using `rstan_package_skeleton`  will create, among other things, the files `R/stanmodels.R` and `tools/make_cc.R`. The contain GPL3 Licence headers. In the first one the package name is the name of my package in the second one it is `rstanarm`. Is this thay way it is supposed to be?
Is it still possible to publish a package that was created using  `rstan_package_skeleton`   under a non-GLP compatible licence (in my case: MIT)?

**Comment by jgabry** [comment]
@jan-glx Very sorry for the slow response. Wasn't ignoring this question, it just got lost in the tons of issues and emails! Anyway, the issue with the license fundamentally has to do with the license for the [Rcpp](https://cran.r-project.org/web/packages/Rcpp/) package. @bgoodri told me that https://github.com/facebook/prophet (which uses RStan and hence Rcpp) gets around this somehow, but I'm not sure exactly what they do.

**Comment by jan-glx** [comment]
I have almost no legal education, but as far as I understand, the Rcpp library and the Libraries are only linked against when a user installs my package so there is no need for me to license my code under GPL because of this (I would need to for binary builds and my lincence would need to be GPL compatible, eg. MIT). However, since rstantools downloads that GPL-licensed `make_cc` source code file from `ratanarm` I am restricted to publish my package under GPL.
You could lift that restriction from users of you package in three ways:
- re-implement `make_cc.R` etc. and licence und MIT or BSD
- ask rstanarm authors to licence these files under MIT or BSD
- perform the download and patching of `make_cc.R` etc. on the installation of your user's packages

BTW, I think you could publish your package under MIT - depending on a GPL R package does not require your package to be GPL (otherwise all R packages would be (since they depend on base).

**Comment by bgoodri** [comment]
That is not how the FSF interprets it. The C++ files generated by the Stan
parser that link with Rcpp (which is GPL'd) are distributed when a package
is built and uploaded to CRAN. See
http://www.gnu.org/licenses/gpl-faq.html#IfLibraryIsGPL
https://www.gnu.org/licenses/gpl-faq.en.html#GPLStaticVsDynamic

**Comment by jan-glx** [comment]
Yes, if the package is distributed as binary this binary package by CRAN it needs to be licensed under GPL in the opinion of the FSF. 
And other than the authors of e.g. the `rubias`, fourierin`, `treespace` and `tokenizers` packages, I probably would not risk myself to be sued by Rcore or Rcpp authors or any of their dependencies.

However, all that does not matter for the distribution of the source version of my package or at least the source code itself. In the current situation I could licence all code of my package under e.g. MIT except for the files added by rstantools which force me to license the combination under GPL.

**Comment by jgabry** [comment]
@bgoodri, if @jan-glx is right about source versions then is there a way we can avoid having to pull the gpl files from rstanarm and still make rstan_package_skeleton do what we need it to do?

**Comment by andrjohns** [comment]
Closing this issue given its age, but feel free to re-open if it was never resolved

**Comment by jan-glx** [comment]
It seems like this issue was indeed fixed in e44ffad1bd439f721e708ce9e64fb75ac819962c and related commits (when switching from downloading accessory files from stanarm codebase to copying files from /inst.
