### ISSUE TITLE
New generics for wrappers around loo::model_weights and loo::model_select

### ISSUE THREAD

**Issue by paul-buerkner** [stan-dev/rstantools#20]
With the release of loo 2.0, I want to support the `model_weights` and `model_select` functions in brms. For this purpose, I need to build wrapper methods around them and I thought it would be a good idea to have a common generic defined in rstantools to minimize naming confusion. I though of the names `loo_weights` and `loo_select`, but I am open to other suggestions.

**Comment by paul-buerkner** [comment]
Or maybe they should go in loo and not in rstantools. In any case, a common generic would be good I think.

**Comment by jgabry** [comment]
Yeah that’s probably a good idea. I think like the loo and waic generics we
can genetics in the loo package for these new functions.

**Comment by jgabry** [comment]
Done in https://github.com/stan-dev/loo/pull/61
