### ISSUE TITLE
PIT computation for count data

### ISSUE THREAD

**Issue by avehtari** [stan-dev/rstantools#22]
rstantools has .loo_pit function
For count data we should compute PIT as described in
Czado, Gneiting, and Held (2009)
Predictive Model Assessment for Count Data
https://onlinelibrary.wiley.com/doi/full/10.1111/j.1541-0420.2009.01191.x
See p. 1255 "a nonrandomized yet uniform version of the PIT histogram"

**Comment by jgabry** [comment]
@avehtari Looking at the paper, it seems we need to be able to evaluate the CDF at the observed counts. 
This is fine but the __rstantools__ package doesn't know if the user fit a Poisson model or a negative binomial model or some other count model (__rstanarm__ knows but users can the PIT stuff without using __rstanarm__). So either we need to add an option for the user to select which CDF to use from some available set that we provide (e.g. `rstantools::loo_pit(object, distribution = "poisson")`),  or make the user pass in a CDF _function_ (e.g. `rstantools::loo_pit(object, cdf = ppois)`). Or am I misunderstanding the method in the paper?

**Comment by avehtari** [comment]
Let's discuss this and some other related issues after two weeks in New York with Dan S.

**Comment by avehtari** [comment]
Closed by #121
