### ISSUE TITLE
warning in `rstan_package_skeleton`: 'No such file or directory'

### ISSUE THREAD

**Issue by sieste** [stan-dev/rstantools#24]
Testing the new step-by-step vignette, the `rstan_package_skeleton` function throws a warning

```r
rstan_package_skeleton(name='rstanlm')
# [output omitted]
Warning message:
In file.remove(DATA) :
  cannot remove file './rstanlm/data', reason 'No such file or directory'
```

The reason is that the condition in

https://github.com/stan-dev/rstantools/blob/31aef4bcdeefeaf98f1f34f31e0715361489a386/R/rstan_package_skeleton.R#L333

is satisfied if the data directory saved in variable `DATA` doesn't exist.

**Comment by jgabry** [comment]
Thanks!
