### ISSUE TITLE
use file.show in step-by-step vignette

### ISSUE THREAD

**Issue by sieste** [stan-dev/rstantools#27]
Using `file.show` instead of `cat(readLines(..., sep='\n'))` seems a bit more elegant

**Comment by jgabry** [comment]
Good call! That’s definitely nicer. I’ll make the switch.

**Comment by sieste** [comment]
I can confirm that everything runs successfully. Well done.

Is there a reason why you included the package `usethis` only under `Suggests` instead of `Imports` or `Depends`?
