### ISSUE TITLE
dead link

### ISSUE THREAD

**Issue by apeterson91** [stan-dev/rstantools#29]
line 229 in the rstan_package_skeleton file has the following dead link

'https://raw.githubusercontent.com/stan-dev/rstanarm/master'

**Comment by jgabry** [comment]
Do you mean that url itself or the ones constructed from it? That url
itself isn’t intended to be used on its own, but rather to be the first
part of the url that gets made on line 230.

Does it fail to download the files when you call rstan_package_skeleton or
just not work if you paste that url from line 229 into a browser? If just
the latter then I don’t think there’s anything to fix, but if it’s
preventing rstan_package_skeleton from downloading the needed files then we
definitely need to fix it. When I run it seems to work but let me know if
it doesn’t work you and I’ll dig into it further.

**Comment by apeterson91** [comment]
Yes, when I ran the function the tools/make_cpp.R file only had a 404:NOT FOUND error.

FWIW, there are also appear to be some inconsistencies in the way the files are set up in the rstan_package_skeleton file (i.e. it still makes an exec folder) and the way it expects to read them (looking for src/stan_files). I suspect this is a result of the changes to rstanarm. Not sure if I should make a separate issue here for that or elsewhere.

**Comment by jgabry** [comment]
Ugh, this was definitely not an issue when we were testing before the
release. Thanks for letting us know! I’ll figure out what’s going on and
report back here.

You’re using rstantools v1.5.0, right? If so it shouldn’t be creating exec
and certainly shouldn’t have broken urls, so I’ll try to sort it out ASAP.

**Comment by apeterson91** [comment]
Hmm. I'm apparently using v1.3.0... but I ran update.packages before I used it. Is v1.5.0 only available via github?

**Comment by jgabry** [comment]
Weird. It's definitely on CRAN: 

https://CRAN.R-project.org/package=rstantools

Which mirror are you using to download it?

**Comment by apeterson91** [comment]
Rstudio's. I've since updated it via another method (via the Rstudio GUI surprisingly enough) and that seems to have resolved the issue. I'm not sure why the base function (nor the devtools version) was updating it...

**Comment by jgabry** [comment]
I’m glad you got it installed, but yeah that’s very strange it couldn’t be
installed the other ways. I’m really not sure how to explain that!
