### ISSUE TITLE
package skeleton travis.yml disallows llvm-toolchain-precise-5.0

### ISSUE THREAD

**Issue by dmenne** [stan-dev/rstantools#38]
When I use the current github version of rstantools to created a skeleton, I get the following error on travis:

```
Disallowing sources: llvm-toolchain-precise-5.0
To add unlisted APT sources, follow instructions in https://docs.travis-ci.com/user/installing-dependencies#Installing-Packages-with-the-APT-Addon
```
[Link to travis docs](https://docs.travis-ci.com/user/installing-dependencies#Installing-Packages-with-the-APT-Addon)

[Link to build](https://travis-ci.org/dmenne/teststan)

I tried to understand the cited reference, but failed to get the syntax right.

Build of rstanarm fails too for the same reason

https://travis-ci.org/stan-dev/rstanarm

**Comment by dmenne** [comment]
Everything works fine with the simple and short default travis.yml

https://github.com/dmenne/teststan/commit/8935947ab700c2bae4cfbf8749bc812f52a52d60

Why does the skeleton use such a complicated travis file?

**Comment by andrjohns** [comment]
Closing this given the move away from Travis CI, and #89, but feel free to re-open if this is still useful/needed
