### ISSUE TITLE
CXX14 Not Defined by R on Windows (3.5.1 and Rtools 3.4)

### ISSUE THREAD

**Issue by saudiwin** [stan-dev/rstantools#40]
Hi - 

I upgraded to the new rstantools and I ran into a confusing issue. The Makevars.win sets CXX_STD as CXX14 , but CXX14 is not defined in the current version of R (3.5.1) with Windows (see https://cran.r-project.org/doc/manuals/r-release/R-exts.html#Using-C_002b_002b14-code). It is possible to set up environmental variables in ~/.R/Makevars.win to define CXX14, but this was rather a pain. 

Is there any reason that CXX14 needs to be used in this file? All of my Stan code on Windows compiles fine with CXX_STD set as CXX11.

**Comment by bgoodri** [comment]
This was a bit premature. RStan >= 2.18.x (which is currently in CRAN purgatory) does require as much of the C++14 standard as is supported by the latest frozen version of Rtools.

**Comment by saudiwin** [comment]
Ok, well it might be good to put out some kind of notice about that. It's entirely possible to enable CXX14 on Windows but it wasn't exactly easy. You need to add the following variables to the ~/.R/Makevars.win file: 

CXX14="$(BINPREF)g++ $(M_ARCH)"
CXX14FLAGS="-O2 -Wall" 
CXX14STD=-std=gnu1y 

There were a couple of issues though even with this modification. First, the ~/.R/Makevars.win file did not exist, and Windows will not let you create a folder with period as the letter, so I had to create the folder via the command line. Then the CXX14STD flag above was not recognized by the compiler, so I had to remove it. Once I did so, though, everything seemed to be compiling fine (of course maybe that's just because I was using Rstan 2.17).

**Comment by bgoodri** [comment]
I think it is going to be fine once rstan 2.18.1 is approved by CRAN.

**Comment by saudiwin** [comment]
Good to hear! I look forward to 2.18's release.
