### ISSUE TITLE
Contradictory statements in Read-and-delete-me

### ISSUE THREAD

**Issue by ksvanhorn** [stan-dev/rstantools#45]
The `Read-and-delete-me` file says

> While developing your package use devtools::install('.', local=FALSE)  to reinstall the package AND recompile Stan programs, or set local=FALSE to skip the recompilation.

So... which is it? Does `local=FALSE` recompile Stan programs or does it skip the recompilation?

**Comment by bgoodri** [comment]
Neither :) The recently-released version of `devtools` with the conscious uncoupling thing going on now says rather than `install` you should specify

> build: if ‘TRUE’ ‘pkgbuild::build()’s the package first: this
          ensures that the installation is completely clean, and
          prevents any binary artefacts (like ‘.o’, ‘.so’) from
          appearing in your local package directory, but is
          considerably slower, because every compile has to start from
          scratch.

**Comment by andrjohns** [comment]
Closing as resolved
