### ISSUE TITLE
my rstan based package cannot be installed on MacOS

### ISSUE THREAD

**Issue by antcalcagni** [stan-dev/rstantools#46]
Hello,
I have developed a rstan based package (rstan: 2.18.2, my os: ubuntu 18.04.01) but when trying to build the package under macOS I find the following error:
====================================================================
make_cc(commandArgs(TRUE))" stan_files/fit_model.stan
Wrote C++ file "stan_files/fit_model.cc"
Error: unexpected symbol in:
"cat(' ', sep = '
cat(system.file('include"
Execution halted
/usr/local/clang7/bin/clang++ -std=gnu++14 -I"/Users/ripley/R/R-patched/include" -DNDEBUG -I"../inst/include" -I"" -DBOOST_DISABLE_ASSERTS -DEIGEN_NO_DEBUG -DBOOST_MATH_OVERFLOW_ERROR_POLICY=errno_on_error -I"/Users/ripley/R/test-3.5/BH/include" -I"/Users/ripley/R/test-3.5/Rcpp/include" -I"/Users/ripley/R/test-3.5/RcppEigen/include" -I"/Users/ripley/R/test-3.5/rstan/include" -I"/Users/ripley/R/test-3.5/StanHeaders/include" -I/usr/local/include -fPIC  -g -O2 -Wall -pedantic -c stan_files/fit_model.cc -o stan_files/fit_model.o
In file included from stan_files/fit_model.cc:3:
In file included from stan_files/fit_model.hpp:18:
In file included from /Users/ripley/R/test-3.5/rstan/include/rstan/rstaninc.hpp:3:
/Users/ripley/R/test-3.5/rstan/include/rstan/stan_fit.hpp:11:10: fatal error: 'stan/version.hpp' file not found
#include <stan/version.hpp> 
====================================================================
Could you please help me with this issue? I cannot see where the error is :-(
Thanks in advance!

**Comment by Voltemand** [comment]
Hi antcalcagni, 

I'm having a very similar problem at the moment. Did you manage to fix the issue?

Thanks!

**Comment by antcalcagni** [comment]
Hi Voltemand,

I just reinstalled rstantools and it worked fine. It seems that problem was fixed in the new version of the rstantools. I created the skeleton of my package with the function inside rstantools. In case your problem would persist, try to use the skeleton of my package (antcalcagni/ssMousetrack), which should compile with no problems.

Best

**Comment by Voltemand** [comment]
Thanks for your response - I actually ended up using a new branch of rstantools I was pointed to [here] (https://discourse.mc-stan.org/t/problem-running-devtools-install-on-simple-rstan-based-package/7046/21).

Thanks for getting back to me though!
