### ISSUE TITLE
my rstan based package fails to compile under macOS

### ISSUE THREAD

**Issue by antcalcagni** [stan-dev/rstantools#47]
Hello,
I have developed [ssMousetrack](https://github.com/antcalcagni/ssMousetrack) a rstan based package (rstan: 2.18.2, my os: ubuntu 18.04.01) but when trying to install the package under macOS I find the following error:

`make_cc(commandArgs(TRUE))" stan_files/fit_model.stan
Wrote C++ file "stan_files/fit_model.cc"
Error: unexpected symbol in:
"cat(' ', sep = '
cat(system.file('include"
Execution halted
/usr/local/clang7/bin/clang++ -std=gnu++14 -I"/Users/ripley/R/R-patched/include" -DNDEBUG -I"../inst/include" -I"" -DBOOST_DISABLE_ASSERTS -DEIGEN_NO_DEBUG -DBOOST_MATH_OVERFLOW_ERROR_POLICY=errno_on_error -I"/Users/ripley/R/test-3.5/BH/include" -I"/Users/ripley/R/test-3.5/Rcpp/include" -I"/Users/ripley/R/test-3.5/RcppEigen/include" -I"/Users/ripley/R/test-3.5/rstan/include" -I"/Users/ripley/R/test-3.5/StanHeaders/include" -I/usr/local/include -fPIC  -g -O2 -Wall -pedantic -c stan_files/fit_model.cc -o stan_files/fit_model.o
In file included from stan_files/fit_model.cc:3:
In file included from stan_files/fit_model.hpp:18:
In file included from /Users/ripley/R/test-3.5/rstan/include/rstan/rstaninc.hpp:3:
/Users/ripley/R/test-3.5/rstan/include/rstan/stan_fit.hpp:11:10: fatal error: 'stan/version.hpp' file not found
#include <stan/version.hpp> `

Could you please help me with this issue? 
Thanks in advance!

**Comment by bgoodri** [comment]
It looks as if you do not have the **StanHeaders** R package installed, or else, it cannot be found where it is installed. It might be the case that you need to follow
https://discourse.mc-stan.org/t/how-to-update-a-package-that-has-stanheaders-and-rstan-in-its-linkingto/6041?u=bgoodri
or
https://discourse.mc-stan.org/t/how-to-update-a-package-that-has-stanheaders-and-rstan-in-its-linkingto-part-ii/6214/4?u=bgoodri

**Comment by antcalcagni** [comment]
Thank you @bgoodri, it seems I was using an old version of rstantools that created Makevars files with old syntax. In the latest version of rstantools, I checked that Makevars files have been now updated according to what is described in your second link. 

I have tested my package with rhub-macos and it seems working now, so it should pass the CRAN test as well. Do you have any suggestions abut that problem before submitting again to CRAN?

Many thanks!

**Comment by bgoodri** [comment]
I think it will be fine. You can try it on https://builder.r-hub.io/ .

**Comment by antcalcagni** [comment]
Fine, thanks.
