### ISSUE TITLE
Using new version

### ISSUE THREAD

**Issue by Voltemand** [stan-dev/rstantools#49]
Hi,

After getting this error:

```
Error: unexpected symbol in:
"cat(' ', sep = '
cat(system.file('include"
Execution halted
```
while trying to make a new package skeleton with **rstantools**. I was told to use a more up to date date branch in [this](https://discourse.mc-stan.org/t/problem-running-devtools-install-on-simple-rstan-based-package/7046/5)  thread in the Stan forums

Branch used: `devtools::install_github("stan-dev/rstantools", ref = " c3c59fb")`

This works great - i.e. I can build the package, hosted [here](https://github.com/Voltemand/rateR) but I have two questions:

1. The package structure I got using the more recent branch is very different to the one described in [this](https://mc-stan.org/rstantools/articles/minimal-rstan-package.html) vignette. Does this represent a progression of the **rstantools** package or is it a throwback?

2. Will the branch I am using be merged into **rstantools** any time soon?

Thanks!

**Comment by bgoodri** [comment]
Yeah, it is the future of rstantools

**Comment by Voltemand** [comment]
Great thanks!
