### ISSUE TITLE
error when I compile my rstan based package

### ISSUE THREAD

**Issue by antcalcagni** [stan-dev/rstantools#54]
Hello,
I've developed my package (ssMousetrack) based on rstantools. The package is on cran and I've never had problems during installation. Now I've tried to install it on a new linux based machine and I've got the following error:

``"/usr/lib/R/bin/Rscript" -e "source(file.path('..', 'tools', 'make_cc.R')); make_cc(commandArgs(TRUE))" stan_files/fit_model.stan
Error: (converted from warning) S3 methods 'print.stanfit', 'as.array.stanfit', 'as.matrix.stanfit', 'as.data.frame.stanfit', 'is.array.stanfit', 'dim.stanfit', 'dimnames.stanfit', 'names.stanfit', 'names<-.stanfit', 'pairs.stanfit', 'loo.stanfit' were declared in NAMESPACE but not found
Execution halted
Makevars:17: recipe for target 'stan_files/fit_model.cc' failed
make: *** [stan_files/fit_model.cc] Error 1
ERROR: compilation failed for package ‘ssMousetrack’
removing ‘/home/stat1/R/x86_64-pc-linux-gnu-library/3.5/ssMousetrack’
Installation failed: Command failed (1)``

It seems something get wrongs with stan headers. What is going wrong?

**Comment by andrjohns** [comment]
Closing this issue given its age, but feel free to re-open if it was never resolved
