### ISSUE TITLE
rstan_package_skeleton: Error - Path does not appear to be inside a project or package

### ISSUE THREAD

**Issue by stephensrmmartin** [stan-dev/rstantools#56]
```
> library(rstantools)
This is rstantools version 1.5.1.9000
> rstan_package_skeleton('ICCier')
Creating package skeleton for package: ICCier
Running usethis::create_package ...
✔ Creating 'ICCier/'
✔ Setting active project to '/home/srmart/ICCier'
✔ Creating 'R/'
✔ Writing 'DESCRIPTION'
Package: ICCier
Title: What the Package Does (One Line, Title Case)
Version: 0.0.0.9000
Authors@R (parsed):
    * First Last <first.last@example.com> [aut, cre] (<https://orcid.org/YOUR-ORCID-ID>)
Description: What the package does (one paragraph).
License: What license it uses
Depends:
    methods,
    R (>= 3.4.0),
    Rcpp (>= 1.0.1)
Imports:
    rstan (>= 2.18.2),
    rstantools (>= 1.5.1)
LinkingTo:
    BH (>= 1.69.0-1),
    Rcpp (>= 1.0.1),
    RcppEigen (>= 0.3.3.5.0),
    rstan (>= 2.18.2),
    StanHeaders (>= 2.18.1)
Encoding: UTF-8
LazyData: true
NeedsCompilation: yes
SystemRequirements: GNU make
✔ Writing 'NAMESPACE'
✔ Writing 'ICCier.Rproj'
✔ Adding '.Rproj.user' to '.gitignore'
✔ Adding '^ICCier\\.Rproj$', '^\\.Rproj\\.user$' to '.Rbuildignore'
✔ Setting active project to '<no active project>'
Error: Path '/home/srmart/' does not appear to be inside a project or package.
```
See code and error above.

I also simply ran the function contents manually, line by line to diagnose the problem. I have to run the code until it breaks.  Then I open the newly create project, create the variables again, change directory to one above the ICCier project directory, then finish running the code.
Even then, I hit snags - I get the roxygen2 DLL error and 'object m not found' error.

The step-by-step guide does not appear to work.
I tried running this in rstudio server, rstudio desktop, and in R via terminal, with and without rstudio=TRUE, open=TRUE.

RStudio version: 1.2.907
R version: 3.5.3
rstantools: Tried both latest CRAN release and github release
Latest CRAN versions of usethis and rstudioapi as well.

**Comment by stephensrmmartin** [comment]
Was able to work around this by modifying the rstan_package_skeleton function to include:
`usethis::proj_set(DIR)`
on line 49.

The next error occurs:
```
> suppressMessages(roxygen2::roxygenise(package.dir = DIR,
+                                       clean = TRUE))
Writing NAMESPACE
Error in getDLLRegisteredRoutines.DLLInfo(dll, addNames = FALSE) : 
  must specify DLL via a “DLLInfo” object. See getLoadedDLLs()
```

**Comment by stephensrmmartin** [comment]
That was worked around by building w/out documentation first, using `pkgbuild::compile_dll()`, then documenting after. I also realized after entirely too much time spent that stan models cannot have dashes in them.

**Comment by jgabry** [comment]
Thanks a lot for the initial report and the follow ups! I haven't had a chance to look thoroughly yet, but we're aiming for a release soon and will be sure to get this sorted out first.

**Comment by ZhaoQii** [comment]
Guys, any new progress on this error?

**Comment by jgabry** [comment]
Yeah, I think this is fixed in PR https://github.com/stan-dev/rstantools/pull/44, which is for the next major release of rstantools. If you want to try it out and report back that would be great!

**Comment by decision-sciences** [comment]
Hi, thanks for sharing this. I reinstall the latest rstantools package from Github. But same error returned again as in the first post:

```{r}
> library("rstantools", lib.loc="/Library/Frameworks/R.framework/Versions/3.6/Resources/library")
This is rstantools version 1.5.1.9000
> rstan_package_skeleton(path = 'test1')
Creating package skeleton for package: test1
Running usethis::create_package ...
Warning: `recursive` is deprecated, please use `recurse` instead
✔ Creating 'test1/'
✔ Setting active project to '/Users/ap/Documents/Columbia/RA CDS/DEEP/DEEP New Pages/test1'
Warning: `recursive` is deprecated, please use `recurse` instead
✔ Creating 'R/'
✔ Writing 'DESCRIPTION'
Package: test1
Title: What the Package Does (One Line, Title Case)
Version: 0.0.0.9000
Authors@R (parsed):
    * First Last <first.last@example.com> [aut, cre] (<https://orcid.org/YOUR-ORCID-ID>)
Description: What the package does (one paragraph).
License: What license it uses
Depends:
    methods,
    R (>= 3.4.0),
    Rcpp (>= 1.0.1)
Imports:
    rstan (>= 2.18.2),
    rstantools (>= 1.5.1)
LinkingTo:
    BH (>= 1.69.0-1),
    Rcpp (>= 1.0.1),
    RcppEigen (>= 0.3.3.5.0),
    rstan (>= 2.18.2),
    StanHeaders (>= 2.18.1)
Encoding: UTF-8
LazyData: true
NeedsCompilation: yes
SystemRequirements: GNU make
✔ Writing 'NAMESPACE'
✔ Writing 'test1.Rproj'
✔ Adding '.Rproj.user' to '.gitignore'
✔ Adding '^test1\\.Rproj$', '^\\.Rproj\\.user$' to '.Rbuildignore'
✔ Setting active project to '<no active project>'
Error: Path '/Users/ap/Documents/Columbia/RA CDS/DEEP/DEEP New Pages/' does not appear to be inside a project or package.
```

**Comment by jgabry** [comment]
Sorry I should have clarified that you would need to install from a particular branch for the time being: 

```r
devtools::install_github("stan-dev/rstantools", ref = "mlysy-rstantools_patch")
```

**Comment by decision-sciences** [comment]
Great, the new function rstan_create_package works now here! But it seems that the structure of package it constructed does not appear to be a git repository (indicated by Github Desktop Mac) so I can't publish it there.

**Comment by jgabry** [comment]
Right, it's not automatically a git repository but it can easily be made into a git repository in the same way as you would turn any existing directory into a git repository using the GitHub Desktop app or command line git. Another option is to use the extra functionality in the **usethis** package (the new `rstan_create_package` is basically a wrapper around [`usethis::create_package()`](https://usethis.r-lib.org/reference/create_package.html)). For example, the [`usethis::use_github()`](https://usethis.r-lib.org/reference/use_github.html) function that will create a github repo for your package after it's created by `rstan_create_package()`. Hope that helps!

**Comment by decision-sciences** [comment]
Thank you very much Jonah for helping me out. BTW for those who also want to convert the existing directory created by rstan_create_package() into a git repository, use usethis::use_git() then it will add necessary files there for you.

**Comment by jgabry** [comment]
Closing since #44 has now been merged into `master`
