### ISSUE TITLE
Including functions defined in additional stan files

### ISSUE THREAD

**Issue by kgori** [stan-dev/rstantools#62]
How do I include a "common_functions.stan" file when using the new package layout?

The old way was to put common functions in the ~`exec/chunks`~ `inst/chunks` directory and then use an `#include` statement in the functions block of the stan model.

The advice in the new layout is (from `Read-and-delete-me`):
> * Additional files to be included by stanmodel definition files
>  (via e.g., #include "mylib.stan") must be placed in any subfolder of 'inst/stan'.

Following this, I modified the example given in the step by step vignette to use an external function, `doubleit`, defined in `inst/stan/include/common_functions.stan`.
Here's the error I get from `pkgbuild::compile_dll()`:
    Function doubleit not found.
     error in 'model_lm' at line 17, column 43
     -------------------------------------------------
       15: model {
       16:   // ... priors, etc.
       17:   y ~ normal(intercept + beta * doubleit(x), sigma);
                                                     ^
       18: }
     -------------------------------------------------
    Error in rstan::stanc(file_name, allow_undefined = TRUE, obfuscate_model_name = FALSE) : 
     failed to parse Stan model 'lm' due to the above error.

The files I'm using are:

`inst/stan/lm.stan`

    // Save this file as inst/stan/lm.stan
    functions {
        #include "common_functions.stan"
    }
    data {
      int<lower=1> N;
      vector[N] x;
      vector[N] y;
    }
    parameters {
      real intercept;
      real beta;
      real<lower=0> sigma;
    }
    model {
      // ... priors, etc.
      y ~ normal(intercept + beta * doubleit(x), sigma);
    }

`inst/stan/include/common_functions.stan`

    vector doubleit(vector xx) {
        return xx * 2;
    }

`R/lm_stan.R`

    # Save this file as `R/lm_stan.R`
    #' Bayesian linear regression with Stan
    #'
    #' @export
    #' @param x Numeric vector of input values.
    #' @param y Numberic vector of output values.
    #' @param ... Arguments passed to `rstan::sampling` (e.g. iter, chains).
    #' @return An object of class `stanfit` returned by `rstan::sampling`
    #'
    lm_stan <- function(x, y, ...) {
        standata <- list(x = x, y = y, N = length(y))
        out <- rstan::sampling(stanmodels$lm, data = standata, ...)
        return(out)
    }

**Comment by kgori** [comment]
Never mind, this is solved :) The include statement should be:

    functions{
    #include /include/common_functions.stan
    }


with no indent, no quotes, with the relative file path and with a leading `/`

**Comment by n8thangreen** [comment]
Is this still the correct way to specify the #inlclude? I've done exactly the same and it appears not to be able to find the file.

**Comment by jgabry** [comment]
Hmm, as far as I know that's still the correct way to do it. Do you have your code on github or online somewhere else where we could take a look?
