### ISSUE TITLE
No leading white space for '#include' of auxilliary stan files

### ISSUE THREAD

**Issue by mlysy** [stan-dev/rstantools#64]
It seems that `rstantools::rstan_config()` errors that it cannot find the auxiliary file when a stan model in the package has e.g.,

```stan
functions {
  #include include/foo.stan
}
```

The issue appears to be that `.make_cc()` within `rstan_config()` uses `rstan::stanc()` to create the C++ source file, whereas perhaps it should be using `rstan::stanc_builder()`.  Having read the documentation in **rstan**, I'm not entirely sure what the difference is, as both functions accept the `isystem` argument, though the function Details only mention `#include`s via `stanc_builder()`.

On my system (OSX), it seems that either (i) replacing `stanc` by `stanc_builder` in `.make_cc`, or (ii) removing the leading spaces in the code above solves the problem.  This was not flagged in the **rstantools** unit tests, because the relevant file `testthat/RStanTest/SimpleModel2.stan` omits the leading spaces when calling `testthat/RStanTest/helper.stan`.

I believe that the preferable solution is (i), save for my confusion about the `stanc/stanc_builder` distinction.  If you agree, then it seems like a very straightforward patch.  Happy to do this myself if that would be helpful.

**Comment by jgabry** [comment]
Good point, that does error for me too. I think I agree with (i) but @bgoodri knows `stan_cbuilder` better than I do, so let’s see if he sees any issue with going that route.

**Comment by bgoodri** [comment]
We created stanc_builder() before stanc in C++ would accept #include
statements. Then when stanc in C++ started accepting #include statements,
we switched to rely on that with rstanarm but left stanc_builder() in rstan
for backward compatibility. But with the new stanc in 2.22, that won't work
anymore so we're going to have to use the C preprocessor to handle the
#includes.

**Comment by mlysy** [comment]
I take it then that `stanc()` is the way forward.  In this case, we may wish to have it replace the call to `stanc_builder()` that gets copied into the package's `R/stanmodels.R`.  The relevant line in the **rstantools** source code is [here](https://github.com/stan-dev/rstantools/blob/d43bf9fb6120d40a60e708853e4b80cdb4689d19/inst/include/sys/stanmodels.R#L12).

**Comment by bgoodri** [comment]
stanc was the way forward but in the near future we won't be able to use it
with the Javascript transpiler, in which case we will have to use the C
preprocessor.

**Comment by mlysy** [comment]
I see.  In any case the `#include` mechanism works as long as there's no leading white space.  I've changed the title of the issue to hopefully be easier for others encountering it to find, and am now closing.
