### ISSUE TITLE
rstantools should update .Rbuildignore and .gitignore

### ISSUE THREAD

**Issue by jgabry** [stan-dev/rstantools#65]
We should have rstantools do this automatically:

From @mcol on Discourse:

> When I switched to rstantools 2.0.0, this is what I added to .Rbuildignore:
> 
> ```
> rcppExports.cpp
> stanExports_*
> ```
> 
> and to .gitignore:
> 
> ```
> *.cc
> *.cpp
> *.h
> ```

(https://discourse.mc-stan.org/t/c-14-standard-requested-but-cxx14-is-not-defined-again-with-rstantools-2-0-0/11432/5)

**Comment by dmenne** [comment]
Gitignore cpp and .h should have directories prepended.

**Comment by andrjohns** [comment]
Closed by #66
