### ISSUE TITLE
Don't delete the common_functions.stan file

### ISSUE THREAD

**Issue by saudiwin** [stan-dev/rstantools#7]
Hi --

This is just a small issue that could be resolved by adding a sentence to the vignette -- if common_functions.stan is deleted from the chunks folder, then the package will fail to load because of this line in `stanmodels.R`:

```
  if (!file.exists(file.path(isystem, "common_functions.stan")))
    isystem <- file.path("inst", "chunks")
  if (!file.exists(file.path(isystem, "common_functions.stan")))
    isystem <- file.path("..", "inst", "chunks")
```

If the file isn't found, then the script will look in the directory above the current one. I'm not sure why this behavior is in the script, but it should be noted in the package vignette. As a consequence, the other includes in chunks won't be copied over to the new library, and lazy loading will fail with "file not found" errors.

Thanks much,

Bob Kubinec

**Comment by jgabry** [comment]
Thanks for reporting this and sorry for the slow response. 

@bgoodri Do you think it makes more sense to not remove the `common_functions.stan` file or just make a note of this?

**Comment by bgoodri** [comment]
I think we should put an `else` into stanmodels.R so that it works.

**Comment by jgabry** [comment]
Do you mean just changing the second `if` above to `else if`?

**Comment by bgoodri** [comment]
Yeah, or maybe adding a third case if that is necessary.

**Comment by jgabry** [comment]
@bgoodri I was going to fix this but I'm not actually sure what the intended behavior is. What was the original reason for these lines? https://github.com/stan-dev/rstanarm/blob/master/R/stanmodels.R#L27-L30

**Comment by bgoodri** [comment]
The original reason was to be able to find the path to the right directory,
but it is not needed as of the feature/2.16 branch of rstanarm.
