### ISSUE TITLE
Makevars doesn't pass CRAN checks

### ISSUE THREAD

**Issue by mcol** [stan-dev/rstantools#71]
The `src/Makevars` generated by `rstantools::rstan_config()` contains GNU extensions, and so doesn't pass the CRAN checks:

```
$ R CMD check --as-cran package.tar.gz
<...>
* checking for GNU extensions in Makefiles ... WARNING
Found the following file(s) containing GNU extensions:
  src/Makevars
Portable Makefiles do not use GNU extensions such as +=, :=, $(shell),
$(wildcard), ifeq ... endif, .NOTPARALLEL See section ‘Writing portable
packages’ in the ‘Writing R Extensions’ manual.
```

**Comment by mcol** [comment]
At least on Linux it's enough to replace 
```
STANHEADERS_SRC = $(shell <all the rest>)`
```
with
```
STANHEADERS_SRC = `<all the rest>`
```
The use of `$shell()` was introduced in 20c00d3477eaa63eea97ac80d65a6fcbeeeebdf6

**Comment by jgabry** [comment]
Thanks @mcol. @bgoodri and/or @mlysy do you know if @mcol's solution will work in general? If so we can just switch to that.

**Comment by bgoodri** [comment]
It is very difficult to get a package to build without using GNU make
extensions. But it should put something to that effect in the DESCRIPTION
file so you do not get a warning from R CMD check.

**Comment by mcol** [comment]
I passed the CRAN checks after replacing `$(shell)` with the apex on Linux. The check is not performed on Windows, so that doesn't need any changes.

**Comment by jgabry** [comment]
> It is very difficult to get a package to build without using GNU make extensions. But it should put something to that effect in the DESCRIPTION file so you do not get a warning from R CMD check.

@bgoodri do you mean rstantools should put "GNU make" in the `System requirements` field of the user's DESCRIPTION file?

**Comment by bgoodri** [comment]
Yes. Does it not do so?

**Comment by jgabry** [comment]
Actually, I think you're right that it already does. looks like we already have that it in the template we use for the description file: 

https://github.com/stan-dev/rstantools/blob/02d84b4c29bafda5b2e1998e6ec6f10c9b3286e1/inst/include/sys/DESCRIPTION#L16

**Comment by jgabry** [comment]
I'd like to do a minor release of rstantools ASAP but not sure what to do about this issue. Do we need to take any immediate action on this given that we do already have GNU make in the System requirements?

**Comment by mcol** [comment]
The DESCRIPTION file generated by the package is fine with "GNU make" listed in the `SystemRequirements` field. I missed that because I was using my own DESCRIPTION file, and I must have missed that line when I moved to rstantools 2.0.0.

**Comment by jgabry** [comment]
Ah ok thanks!
