### ISSUE TITLE
Are ALL stan models recompiled when a package is updated?

### ISSUE THREAD

**Issue by EoinTravers** [stan-dev/rstantools#80]
Well done on a great tool.

I'm interested in developing an internal package containing of compiled versions of models that are frequently used by my colleagues and I, kind of like an in-house version of [hBayesDM](https://github.com/CCS-Lab/hBayesDM).

Let's say the package is configured with `rstan_create_package()`, and installed (from GitHub) on several machines. The package is then updated to add a new model. Will installing the update require that all the existing models, which haven't changed between versions, be recompiled, or can this be avoided?

Thanks.

**Comment by jgabry** [comment]
> Well done on a great tool.

Thanks, glad you like it! 

> Let's say the package is configured with rstan_create_package(), and installed (from GitHub) on several machines. The package is then updated to add a new model. Will installing the update require that all the existing models, which haven't changed between versions, be recompiled, or can this be avoided?

Unfortunately I'm not sure how to avoid that. I'm pretty sure that the functions for installing R packages from GitHub replace the entire package source code every time, so everything would need to get recompiled. In theory I could see it being possible to just replace the changed parts of the package when installing from GitHub but I'm not aware of a tool that does that at the moment. But maybe it exists and I just don't know about it.

**Comment by EoinTravers** [comment]
Thanks. 
I guess the alternative would have to be a wrapper that compiles and saves a model the first time it's used, and loads the compiled version otherwise.

**Comment by andrjohns** [comment]
Closing this as it can't be resolved by `rstantools` - there currently isn't a mechanism for only partially replacing installed R packages when updating/re-installing
