### ISSUE TITLE
configure files in packages made with rstan_create_package() produces a note when running R CMD check

### ISSUE THREAD

**Issue by AngusMcLure** [stan-dev/rstantools#82]
Minor issue, with an easy fix. 

rstantools version: 2.1.1
R version: 4.0.3
Platform: OS X

When checking a package that I set up using ```rstan_create_package```, I got a warning  (new to R 4.0?) prompting me to add the ```checkbashisms``` script to my $PATH. I did this, resolving the warning, but producing a new NOTE:

```
checking top-level files ... NOTE
script configure does not appear to have a #! interpreter line
```

I eliminated the NOTE (both on my local OS X build and on win-builder) by making small changes to ```configure``` and ```conigure.win``` automatically generated by ```rstan_create_package```. The default ```configure``` is:

```
# Generated by rstantools.  Do not edit by hand.

#! /bin/sh
"${R_HOME}/bin/Rscript" -e "rstantools::rstan_config()"
```

Noting, but disobeying the imperative not to edit, I reordered the first two lines so that the ```#!``` lines is at the top. i.e.:

```
#! /bin/sh
# Generated by rstantools.  Do not edit by hand.
"${R_HOME}/bin/Rscript" -e "rstantools::rstan_config()"
```

I did the same for ```configure.win```

The package now passes ```devtools::check()``` and ```devtools::check_win_release()```

**Comment by jgabry** [comment]
Thanks for letting us know about this and sharing the fix. Glad you were able to workaround it. The edit of reordering the first two lines seems fine to me, so I guess we should just go ahead and do that in rstantools. @bgoodri Is that fine by you too?

**Comment by AngusMcLure** [comment]
No problem. Thanks for all your work in building, developing and maintaining these tools.
Angus

**Comment by bgoodri** [comment]
Yeah, we can put the # Generated by rstantools ... thing on the second line
to avoid the need for the checkbashisms script.
