### ISSUE TITLE
Github actions workflow - test against rstan experimental or preview?

### ISSUE THREAD

**Issue by andrjohns** [stan-dev/rstantools#93]
In the Github actions workflow that I've added, `rstantools` is tested with all combinations of CRAN & preview `rstan`/`StanHeaders` (where the preview packages are those provided by the `"https://mc-stan.org/r-packages/"` repo). Should these instead test against the `experimental` branch of the `rstan` repo? That could catch any incompatibilities sooner after their introduction.

@hsbadr ?

**Comment by hsbadr** [comment]
I think the `experimental` branch should get merged into `develop` at some point. Then, the GHA workflow would test the development version (from GitHub `develop` branch or https://mc-stan.org/r-packages/) and CRAN release. All other versions are for temporary transition (backward compatibility on CRAN and the big jump from v2.21 to v2.26+ or v2.29+).

**Comment by andrjohns** [comment]
Ah I see, make sense!
